backend:
  name: auth0
  repo: aiekodevos/Peter-Lagast
  branch: main

auth:
  client_id: a6VEMmaWGOIQRU2p5tdFiqSoGtNWQ8CP
  auth_endpoint: https://dev-1j0zgguaeogv50j2.us.auth0.com/authorize

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "werken"
    label: "Werken"
    folder: "content/werken"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"

      - label: "Jaar"
        name: "year"
        widget: "number"

      - label: "Afbeelding"
        name: "image"
        widget: "image"

      - label: "Beschrijving"
        name: "body"
        widget: "markdown"
