backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "werken"
    label: "Werken"
    folder: "content/werken"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - { label: "Jaar", name: "jaar", widget: "string" }
