backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "werken"
    label: "Werken"
    folder: "content/werken"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - { label: "Omschrijving", name: "body", widget: "markdown" }
      - label: "Jaar"
        name: "year"
        widget: "select"
        options: ["2025", "2024", "2023", "2022", "2021"]
